### ISSUE TITLE
Out of range zipcodes breaking DS API

### ISSUE THREAD

**Issue by isaiah-j** [fp-rap-build/data-science#7]
Sending a zipcode that isn't from Spokane will cause a internal server error breaking the frontend

testing with zipcode 16504 (Erie, PA)

<img width="960" alt="error1" src="https://user-images.githubusercontent.com/66272034/112021492-ba350180-8b07-11eb-942c-795ca9638af1.PNG">

zipcode 99204 (Spokane)

<img width="684" alt="error2" src="https://user-images.githubusercontent.com/66272034/112021557-cb7e0e00-8b07-11eb-92fd-0a618e50d743.PNG">

**Comment by iesous-kurios** [comment]
Should be fixed now.

**Comment by iesous-kurios** [comment]
@isaiah-j  I think my most recent push fixed this issue.
